defaultBaseImage: ghcr.io/distroless/static:latest

builds:
  - id: kubemox 
    dir: cmd 
    main: main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - -s
      - -w
      - "{{ .Env.LDFLAGS }}"
    sbom: none
