---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3s-default

servers: 1
agents: 0
image: docker.io/rancher/k3s:v1.33.3-k3s1

# Map host port 80 to container port 80 via the k3d load balancer
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer

registries:
  create:
    name: registry
    hostPort: "5000"
  config: |
    mirrors:
      "registry:5000":
        endpoint:
          - http://registry:5000
