---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubemox 
rules:
# Custom Resources
- apiGroups: ["proxmox.alperen.cloud"]
  resources: 
  - "managedvirtualmachines"
  - "managedvirtualmachines/finalizers"
  - "managedvirtualmachines/status"
  - "virtualmachines"
  - "virtualmachines/finalizers"
  - "virtualmachines/status"
  - "virtualmachinesets"
  - "virtualmachinesets/finalizers"
  - "virtualmachinesets/status"
  - "virtualmachinesnapshots"
  - "virtualmachinesnapshots/finalizers"
  - "virtualmachinesnapshots/status"
  - "virtualmachinesnapshotpolicies"
  - "virtualmachinesnapshotpolicies/finalizers"
  - "virtualmachinesnapshotpolicies/status"
  - "virtualmachinetemplates"
  - "virtualmachinetemplates/finalizers"
  - "virtualmachinetemplates/status"
  - "containers"
  - "containers/finalizers"
  - "containers/status"
  - "customcertificates"
  - "customcertificates/finalizers"
  - "customcertificates/status"
  - "storagedownloadurls"
  - "storagedownloadurls/finalizers"
  - "storagedownloadurls/status"
  - "proxmoxconnections"
  - "proxmoxconnections/finalizers"
  - "proxmoxconnections/status"
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# Events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
## Leader election
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
## List CRDs
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
  - get
# Certificates
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]