# permissions for end users to edit proxmoxconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubemox
    app.kubernetes.io/managed-by: kustomize
  name: proxmox-proxmoxconnection-editor-role
rules:
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - proxmoxconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - proxmoxconnections/status
  verbs:
  - get
