# permissions for end users to view storagedownloadurls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: storagedownloadurl-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubemox
    app.kubernetes.io/part-of: kubemox
    app.kubernetes.io/managed-by: kustomize
  name: storagedownloadurl-viewer-role
rules:
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - storagedownloadurls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - storagedownloadurls/status
  verbs:
  - get
