# permissions for end users to view proxmoxconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubemox
    app.kubernetes.io/managed-by: kustomize
  name: proxmox-proxmoxconnection-viewer-role
rules:
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - proxmoxconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxmox.alperen.cloud
  resources:
  - proxmoxconnections/status
  verbs:
  - get
