apiVersion: v1
kind: Secret
metadata:
  name: proxmox-credentials
  namespace: kubemox-system
stringData:
  token: "PROXMOX_TOKEN_SECRET"
---
apiVersion: proxmox.alperen.cloud/v1alpha1
kind: ProxmoxConnection
metadata:
  labels:
    app.kubernetes.io/name: kubemox
    app.kubernetes.io/managed-by: kustomize
  name: proxmoxconnection-sample-secret
spec:
  endpoint: "PROXMOX_ENDPOINT"
  tokenID: "PROXMOX_TOKEN_ID"
  secretFrom:
    name: proxmox-credentials
    namespace: kubemox-system
    key: token
  insecureSkipVerify: true
