apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachineSet
metadata:
  labels:
    app.kubernetes.io/name: virtualmachineset
    app.kubernetes.io/instance: virtualmachineset-sample
    app.kubernetes.io/part-of: kubemox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubemox
  name: kubernetes-master
spec:
  connectionRef:
    # Name of the ProxmoxConnection resource
    name: proxmoxconnection-sample
  # Number of VMs to be created
  replicas: 1
  nodeName: lowtower
  template:
    # Name of the template to be cloned
    name: fedora-template 
    # CPU cores to be allocated to the VM
    cores: 4
    # CPU sockets to be allocated to the VM
    socket: 1
    # Memory to be allocated to the VM
    memory: 4096 # As MB
    # Deletion protection is whether to delete VM from Proxmox or not
    deleteProtection: false
    # VM should be started any time found in stopped state
    enableAutostart: true
    # Disk used by the VM
    disk: 
      - storage: nvme 
        size: 50 # As GB
        device: scsi
    # Network interfaces used by the VM
    network:
      - model: virtio
        bridge: vmbr0
---
apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachineSet
metadata:
  labels:
    app.kubernetes.io/name: virtualmachineset
    app.kubernetes.io/instance: virtualmachineset-sample
    app.kubernetes.io/part-of: kubemox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubemox
  name: kubernetes-worker
spec:
  # Number of VMs to be created
  replicas: 2
  nodeName: lowtower
  template:
    # Name of the template to be cloned
    name: fedora-template 
    # CPU cores to be allocated to the VM
    cores: 8
    # CPU sockets to be allocated to the VM
    socket: 1
    # Memory to be allocated to the VM
    memory: 32768 # As MB 
    # Deletion protection is whether to delete VM from Proxmox or not
    deleteProtection: false
    # VM should be started any time found in stopped state
    enableAutostart: true
    # Disk used by the VM
    disk: 
      - storage: nvme 
        size: 50 # As GB
        device: scsi
    # Network interfaces used by the VM
    network:
      - model: virtio
        bridge: vmbr0
