apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachineSnapshotPolicy
metadata:
  labels:
    app.kubernetes.io/name: virtualmachinesnapshotpolicy
    app.kubernetes.io/instance: virtualmachinesnapshotpolicy-sample
    app.kubernetes.io/part-of: kubemox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubemox
  name: virtualmachinesnapshotpolicy-sample
spec:
  connectionRef:
    # Name of the ProxmoxConnection resource
    name: proxmoxconnection-sample
  snapshotSchedule: "*/30 * * * *" # Every 30 minutes
  namespaceSelector:
    namespaces: ["default", "my-namespace"]
  labelSelector:
    matchLabels:
      app.kubernetes.io/name: virtualmachine-sample-clone
