# This manifest is used to create a Virtual Machine from an existing template.
apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachine
metadata:
  name: virtualmachine-sample-clone
spec:
  name: virtualmachine-sample-clone
  # Name of the node where the VM will be created
  nodeName: lowtower
  # Deletion protection is whether to delete VM from Proxmox or not
  deletionProtection: false
  # VM should be started any time found in stopped state
  enableAutoStart: true
  connectionRef:
    # Name of the ProxmoxConnection resource
    name: proxmoxconnection-sample
  template:
    # Name of the template to be cloned
    name: fedora-template 
    # CPU cores to be allocated to the VM
    cores: 2
    # CPU sockets to be allocated to the VM
    socket: 1
    # Memory to be allocated to the VM
    memory: 4096 # As MB
    # Disk used by the VM
    disk: 
      - storage: local-lvm 
        size: 60 # As GB
        device: scsi0
      - storage: local-lvm 
        size: 20 # As GB
        device: scsi1
    # Network interfaces used by the VM
    network:
      - model: virtio
        bridge: vmbr0
    pciDevices:
      - deviceID: "0000:03:00.2"
        type: "raw"
        primaryGPU: true
        pcie: true
  # Optional field to add additional features to the VM that doesn't included in the spec
  additionalConfig:                                         
    balloon: "0"                                            
    cpu: host                                               
    vga: type=virtio,memory=16   