apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachineSet
metadata:
  labels:
    app.kubernetes.io/name: virtualmachineset
    app.kubernetes.io/instance: virtualmachineset-sample
    app.kubernetes.io/part-of: kubemox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubemox
  name: virtualmachineset-test
spec:
  # Number of VMs to be created
  replicas: 3
  nodeName: lowtower
  template:
    # Name of the template to be cloned
    name: fedora-template 
    # CPU cores to be allocated to the VM
    cores: 2
    # CPU sockets to be allocated to the VM
    socket: 1
    # Memory to be allocated to the VM
    memory: 4096 # As MB
    # Disk used by the VM
    disk: 
      - storage: nvme 
        size: 50 # As GB
        type: scsi
    # Network interfaces used by the VM
    network:
      - model: virtio
        bridge: vmbr0
