# This manifest is used to create a Virtual Machine from an existing template.
apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachine
metadata:
  name: virtualmachine-sample-clone
spec:
  name: virtualmachine-sample-clone
  # Name of the node where the VM will be created
  nodeName: lowtower
  # Deletion protection is whether to delete VM from Proxmox or not
  deletionProtection: false
  # VM should be started any time found in stopped state
  enableAutostart: true
  template:
    # Name of the template to be cloned
    name: fedora-template 
    # CPU cores to be allocated to the VM
    cores: 2
    # CPU sockets to be allocated to the VM
    socket: 1
    # Memory to be allocated to the VM
    memory: 4096 # As MB
    # Disk used by the VM
    disk: 
      - storage: local-lvm 
        size: 50 # As GB
        device: scsi0
      - storage: local-lvm 
        size: 20 # As GB
        device: scsi1
    # Network interfaces used by the VM
    network:
      - model: virtio
        bridge: vmbr0
