apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: kubemox
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinetemplate-sample
spec:
  connectionRef:
    # Name of the ProxmoxConnection resource
    name: proxmoxconnection-sample
  name: virtualmachinetemplate-sample
  node: lowtower
  imageConfig:
    content: "iso" 
    filename: "bionic-server-cloudimg-amd64.img"
    node: "lowtower"
    storage: "local" 
    url: "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
  cloudInitConfig:
    user: "ubuntu"
    passwordFrom: 
        name: cloudinit-secret
        key: password
    upgradePackages: true
    custom:
      userData: "ubuntu-cloud-config-workers.yaml" # That should be inside snippets folder in Proxmox node
  virtualMachineConfig:
    sockets: 1
    cores: 2
    memory: 2048
    network: 
      model: virtio 
      bridge: vmbr0 