apiVersion: proxmox.alperen.cloud/v1alpha1
kind: VirtualMachineSet
metadata:
  name: talos-master 
spec:
  connectionRef:
    # Name of the ProxmoxConnection resource
    name: proxmoxconnection-sample
  deletionProtection: false 
  enableAutoStart: false
  # Number of VMs to be created
  replicas: 3
  nodeName: NODE_NAME 
  template:
    # Name of the template to be cloned
    name: talos-template 
    # CPU cores to be allocated to the VM
    cores: 4
    # CPU sockets to be allocated to the VM
    socket: 1
    # Memory to be allocated to the VM
    memory: 4096 # As MB
    # Disk used by the VM
    disk: 
      - storage: local-lvm
        size: 50 # As GB
        device: scsi0
    # Network interfaces used by the VM
    network:
      - model: virtio
        bridge: vmbr0