name: verify

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'charts/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'charts/**'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run mage.go
        run: go run mage.go